version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
